//! SMART Health Check-in matcher.
//!
//! Eligibility rule (see `docs/profiles/org-iso-mdoc.md` §"Wallet matcher contract"):
//!
//! 1. The Credential Manager request bytes contain `org-iso-mdoc`. **Required
//!    self-filter** — the AndroidX `registry-provider` path passes an empty
//!    `protocolTypes` list down to the GMS bridge
//!    (`RegistryManagerProviderPlayServicesImpl`), so the host invokes every
//!    registered DC matcher for every DC API request and the matcher decides.
//!    See "Sources of truth" at the bottom of `wallet-android/app/matcher/README.md`.
//! 2. Inside `data.deviceRequest` (base64url-no-pad of CBOR), the literal UTF-8
//!    bytes of the doctype `org.smarthealthit.checkin.1` appear somewhere. CBOR
//!    encodes tstrs verbatim, so substring search is sufficient — no CBOR parser
//!    needed. The host may hand the matcher either plain JSON or a wrapper with
//!    the request JSON escaped as a string, so both shapes are accepted.
//!
//! If both hold, emit one `AddStringIdEntry` for the SMART Check-in entry,
//! decorated with the SMART starburst icon embedded at compile time.

pub mod bindings;
pub mod credman;
pub mod logger;

use std::ffi::CString;

use crate::credman::CredmanApi;

pub const PROTOCOL_ID: &str = "org-iso-mdoc";
pub const DOCTYPE: &str = "org.smarthealthit.checkin.1";
pub const DEFAULT_ENTRY_ID: &str = "checkin-default";
pub const DEFAULT_TITLE: &str = "SMART Health Check-in";
pub const DEFAULT_SUBTITLE: &str = "Choose what to share before anything is sent";
pub const DEFAULT_DISCLAIMER: &str =
    "Continue to review the requested health information in the SMART app.";
pub const DEFAULT_FIELD_NAME: &str = "Your health info";
pub const DEFAULT_FIELD_VALUE: &str =
    "You choose what to share. Continue to review details in SMART Health Check-in.";

/// Stable v2 set id. The host uses (cred_id, set_id, set_index) as a
/// composite key when the user picks an entry; we always emit one set
/// containing one entry, so a fixed id is fine.
pub const ENTRY_SET_ID: &str = "smart-health-checkin-set";

/// Metadata payload echoed back to our HandlerActivity in
/// `request.selectedEntryId` when the user picks the entry. JSON shape
/// matches the upstream CMWallet convention.
pub const ENTRY_METADATA_JSON: &str = "{\"id\":\"checkin-default\",\"provider_idx\":0}";

/// Embedded entry icon (192×192 PNG, RGBA). Generated by
/// `assets/build-icon.ts` from the upstream SMART starburst SVG. Re-render
/// at a different size by editing the script's `--default` arg and rebuilding.
pub const ENTRY_ICON_PNG: &[u8] = include_bytes!("../assets/icon.png");

/// Result of inspecting a Credential Manager request. Useful for tests; the
/// matcher binary just discards it after emitting the entry.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MatchOutcome {
    NotApplicable,
    Eligible,
}

/// Emits one entry to the picker through whichever surface the host
/// supports. Modern Credential Manager hosts (Play Services + AndroidX
/// registry-provider 1.0.0-SNAPSHOT) read entries from the v2
/// credential-set surface; older hosts only have the v1 single-entry
/// surface. We probe `GetWasmVersion` and pick the right path.
///
/// Mirrors `tools/matcher-c/c_yes_matcher.c` field-by-field: title + subtitle
/// + disclaimer above the entry, one (name, value) field row beneath.
fn emit_one_entry<C: CredmanApi>(
    api: &mut C,
    title: &str,
    subtitle: &str,
    disclaimer: &str,
    field_name: &str,
    field_value: &str,
) {
    let cred_id = CString::new(DEFAULT_ENTRY_ID).unwrap_or_default();
    let title_c = CString::new(title).ok();
    let subtitle_c = CString::new(subtitle).ok();
    let disclaimer_c = CString::new(disclaimer).ok();
    let field_name_c = CString::new(field_name).ok();
    let field_value_c = CString::new(field_value).ok();

    if api.get_wasm_version() >= 2 {
        let set_id = CString::new(ENTRY_SET_ID).unwrap_or_default();
        let metadata = CString::new(ENTRY_METADATA_JSON).ok();

        api.add_entry_set(&set_id, 1);
        api.add_entry_to_set(
            &cred_id,
            Some(ENTRY_ICON_PNG),
            title_c.as_deref(),
            subtitle_c.as_deref(),
            disclaimer_c.as_deref(),
            None,
            metadata.as_deref(),
            &set_id,
            0,
        );
        if let Some(name) = field_name_c.as_deref() {
            api.add_field_to_entry_set(&cred_id, name, field_value_c.as_deref(), &set_id, 0);
        }
        return;
    }

    // v1 fallback (legacy hosts).
    api.add_string_id_entry(
        &cred_id,
        Some(ENTRY_ICON_PNG),
        title_c.as_deref(),
        subtitle_c.as_deref(),
        disclaimer_c.as_deref(),
        None,
    );
    if let Some(name) = field_name_c.as_deref() {
        api.add_field(&cred_id, name, field_value_c.as_deref());
    }
}

/// Diagnostic matcher: always emits one entry, regardless of request shape.
///
/// Used by the `yes` bin to localize "Your info wasn't found" failures.
/// If swapping in `yes.wasm` makes our entry appear in the picker, the
/// real matcher's eligibility logic was rejecting the request. If the entry
/// *still* doesn't appear, the failure is upstream of the matcher
/// (registration not active, host not loading the WASM, etc.).
///
/// The subtitle exposes the request size and the host's reported WASM ABI
/// version so it's obvious in the picker which build is loaded and which
/// surface is in use.
pub fn always_emit<C: CredmanApi>(api: &mut C) {
    let request = api.get_request_buffer();
    let creds = api.get_registered_data();
    let version = api.get_wasm_version();
    let subtitle = format!(
        "always-yes · ABI v{} · req {}B · creds {}B",
        version,
        request.len(),
        creds.len(),
    );
    emit_one_entry(
        api,
        "SMART Health Check-in (diag)",
        &subtitle,
        DEFAULT_DISCLAIMER,
        DEFAULT_FIELD_NAME,
        DEFAULT_FIELD_VALUE,
    );
}

/// Top-level entry. Reads request + credentials from the host, decides
/// eligibility, and emits zero or one entry through the host's preferred
/// surface (v2 entry-set if available, v1 string-id otherwise).
pub fn run<C: CredmanApi>(api: &mut C) -> MatchOutcome {
    let request = api.get_request_buffer();
    if !request_is_eligible(&request) {
        return MatchOutcome::NotApplicable;
    }

    let creds = api.get_registered_data();
    let display = parse_display_from_credentials_blob(&creds);

    emit_one_entry(
        api,
        &display.title,
        &display.subtitle,
        &display.disclaimer,
        &display.field_name,
        &display.field_value,
    );

    MatchOutcome::Eligible
}

/// True iff the outer Credential Manager request bytes contain both:
///   - the literal `"org-iso-mdoc"` substring somewhere (the matcher's only
///     protocol gate — the host doesn't pre-filter, so we have to),
///   - a `data.deviceRequest` whose base64url decode contains our doctype.
pub fn request_is_eligible(request: &[u8]) -> bool {
    if !contains_subslice(request, PROTOCOL_ID.as_bytes()) {
        return false;
    }
    if contains_subslice(request, DOCTYPE.as_bytes()) {
        return true;
    }

    for device_request_b64u in [
        find_string_value(request, b"deviceRequest"),
        find_escaped_string_value(request, b"deviceRequest"),
    ].into_iter().flatten() {
        if decode_base64url_no_pad(device_request_b64u)
            .is_some_and(|bytes| contains_subslice(&bytes, DOCTYPE.as_bytes()))
        {
            return true;
        }
    }

    false
}

/// Find `"<key>": "<value>"` and return the raw `<value>` bytes.
///
/// Walks the buffer for `"<key>"`, skips JSON whitespace + the colon, expects
/// an opening quote, then reads up to the closing quote. The deviceRequest
/// value is base64url (alphabet A-Z a-z 0-9 - _) — no escape sequences, so a
/// strict scan is sufficient. Other potential matches (the same key as a
/// suffix of a different key, e.g. `xdeviceRequest`) are rejected by checking
/// the byte before the opening quote.
pub fn find_string_value<'a>(haystack: &'a [u8], key: &[u8]) -> Option<&'a [u8]> {
    let mut search_from = 0usize;
    let key_len = key.len();
    while let Some(rel) = position_of(&haystack[search_from..], key) {
        let pos = search_from + rel;
        if pos == 0 || haystack[pos - 1] != b'"' {
            search_from = pos + 1;
            continue;
        }
        let after_key = pos + key_len;
        if after_key >= haystack.len() || haystack[after_key] != b'"' {
            search_from = pos + 1;
            continue;
        }
        let mut i = after_key + 1;
        while i < haystack.len() && is_json_ws(haystack[i]) {
            i += 1;
        }
        if i >= haystack.len() || haystack[i] != b':' {
            search_from = pos + 1;
            continue;
        }
        i += 1;
        while i < haystack.len() && is_json_ws(haystack[i]) {
            i += 1;
        }
        if i >= haystack.len() || haystack[i] != b'"' {
            search_from = pos + 1;
            continue;
        }
        i += 1;
        let start = i;
        while i < haystack.len() && haystack[i] != b'"' {
            i += 1;
        }
        if i >= haystack.len() {
            return None;
        }
        return Some(&haystack[start..i]);
    }
    None
}

/// Find a string value inside an escaped JSON string, e.g.
/// `{\"deviceRequest\":\"...\"}` embedded in an outer request wrapper.
pub fn find_escaped_string_value<'a>(haystack: &'a [u8], key: &[u8]) -> Option<&'a [u8]> {
    let mut search_from = 0usize;
    let key_len = key.len();
    while let Some(rel) = position_of(&haystack[search_from..], key) {
        let pos = search_from + rel;
        if pos < 2 || haystack[pos - 2] != b'\\' || haystack[pos - 1] != b'"' {
            search_from = pos + 1;
            continue;
        }
        let after_key = pos + key_len;
        if after_key + 1 >= haystack.len()
            || haystack[after_key] != b'\\'
            || haystack[after_key + 1] != b'"'
        {
            search_from = pos + 1;
            continue;
        }

        let mut i = after_key + 2;
        while i < haystack.len() && is_json_ws(haystack[i]) {
            i += 1;
        }
        if i >= haystack.len() || haystack[i] != b':' {
            search_from = pos + 1;
            continue;
        }
        i += 1;
        while i < haystack.len() && is_json_ws(haystack[i]) {
            i += 1;
        }
        if i + 1 >= haystack.len() || haystack[i] != b'\\' || haystack[i + 1] != b'"' {
            search_from = pos + 1;
            continue;
        }
        i += 2;
        let start = i;
        while i + 1 < haystack.len() && !(haystack[i] == b'\\' && haystack[i + 1] == b'"') {
            i += 1;
        }
        if i + 1 >= haystack.len() {
            return None;
        }
        return Some(&haystack[start..i]);
    }
    None
}

fn position_of(haystack: &[u8], needle: &[u8]) -> Option<usize> {
    if needle.is_empty() || needle.len() > haystack.len() {
        return None;
    }
    haystack.windows(needle.len()).position(|w| w == needle)
}

fn contains_subslice(haystack: &[u8], needle: &[u8]) -> bool {
    position_of(haystack, needle).is_some()
}

fn is_json_ws(b: u8) -> bool {
    matches!(b, b' ' | b'\t' | b'\n' | b'\r')
}

/// Decode base64url (no padding) bytes into raw bytes.
/// Permissive on input; returns None on malformed alphabet.
pub fn decode_base64url_no_pad(input: &[u8]) -> Option<Vec<u8>> {
    let mut bits = 0u32;
    let mut acc_bits = 0u8;
    let mut out = Vec::with_capacity(input.len() * 3 / 4);
    for &b in input {
        let v: u32 = match b {
            b'A'..=b'Z' => (b - b'A') as u32,
            b'a'..=b'z' => (b - b'a' + 26) as u32,
            b'0'..=b'9' => (b - b'0' + 52) as u32,
            b'-' => 62,
            b'_' => 63,
            b'=' => continue, // tolerate stray padding
            _ => return None,
        };
        bits = (bits << 6) | v;
        acc_bits += 6;
        while acc_bits >= 8 {
            acc_bits -= 8;
            out.push(((bits >> acc_bits) & 0xff) as u8);
        }
    }
    Some(out)
}

#[derive(Debug)]
struct Display {
    id: String,
    title: String,
    subtitle: String,
    disclaimer: String,
    field_name: String,
    field_value: String,
}

impl Default for Display {
    fn default() -> Self {
        Display {
            id: DEFAULT_ENTRY_ID.into(),
            title: DEFAULT_TITLE.into(),
            subtitle: DEFAULT_SUBTITLE.into(),
            disclaimer: DEFAULT_DISCLAIMER.into(),
            field_name: DEFAULT_FIELD_NAME.into(),
            field_value: DEFAULT_FIELD_VALUE.into(),
        }
    }
}

/// Pull title / subtitle / id / disclaimer / field strings from the
/// registered credentials blob if present; fall back to compiled-in
/// defaults otherwise.
///
/// The blob shape mirrors `Registration.kt::buildCredentialsBlob`:
///   {"credentials":[{
///     "id":"…", "title":"…", "subtitle":"…",
///     "disclaimer":"…", "fieldName":"…", "fieldValue":"…"
///   }, …]}
///
/// Same string-scan trick the request scanner uses — no real JSON parser
/// needed, and the matcher stays tiny.
fn parse_display_from_credentials_blob(blob: &[u8]) -> Display {
    let mut display = Display::default();
    for (key, slot) in [
        (b"id".as_slice(),         &mut display.id),
        (b"title".as_slice(),      &mut display.title),
        (b"subtitle".as_slice(),   &mut display.subtitle),
        (b"disclaimer".as_slice(), &mut display.disclaimer),
        (b"fieldName".as_slice(),  &mut display.field_name),
        (b"fieldValue".as_slice(), &mut display.field_value),
    ] {
        if let Some(bytes) = find_string_value(blob, key) {
            if let Ok(s) = std::str::from_utf8(bytes) {
                if !s.is_empty() {
                    *slot = s.to_owned();
                }
            }
        }
    }
    display
}

#[cfg(test)]
pub(crate) mod test_support {
    /// base64url-no-pad helper for tests / fixtures.
    pub fn base64url_no_pad(input: &[u8]) -> String {
        let alphabet = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
        let mut out = String::with_capacity((input.len() + 2) / 3 * 4);
        let chunks = input.chunks_exact(3);
        let remainder = chunks.remainder();
        for chunk in chunks {
            let n = (chunk[0] as u32) << 16 | (chunk[1] as u32) << 8 | (chunk[2] as u32);
            out.push(alphabet[((n >> 18) & 0x3f) as usize] as char);
            out.push(alphabet[((n >> 12) & 0x3f) as usize] as char);
            out.push(alphabet[((n >> 6) & 0x3f) as usize] as char);
            out.push(alphabet[(n & 0x3f) as usize] as char);
        }
        match remainder.len() {
            1 => {
                let n = (remainder[0] as u32) << 16;
                out.push(alphabet[((n >> 18) & 0x3f) as usize] as char);
                out.push(alphabet[((n >> 12) & 0x3f) as usize] as char);
            }
            2 => {
                let n = (remainder[0] as u32) << 16 | (remainder[1] as u32) << 8;
                out.push(alphabet[((n >> 18) & 0x3f) as usize] as char);
                out.push(alphabet[((n >> 12) & 0x3f) as usize] as char);
                out.push(alphabet[((n >> 6) & 0x3f) as usize] as char);
            }
            _ => {}
        }
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decode_base64url_roundtrip() {
        let data = b"\x00\x01\x02\xfe\xff\x10\x20";
        let s = test_support::base64url_no_pad(data);
        let decoded = decode_base64url_no_pad(s.as_bytes()).unwrap();
        assert_eq!(decoded, data);
    }

    #[test]
    fn finds_top_level_string_value() {
        let json = br#"{"x":1,"deviceRequest":"abc-_123","y":"other"}"#;
        assert_eq!(find_string_value(json, b"deviceRequest"), Some(&b"abc-_123"[..]));
    }

    #[test]
    fn finds_escaped_string_value() {
        let json = br#"{"requestJson":"{\"deviceRequest\":\"abc-_123\"}"}"#;
        assert_eq!(find_escaped_string_value(json, b"deviceRequest"), Some(&b"abc-_123"[..]));
    }

    #[test]
    fn ignores_substring_keys() {
        let json = br#"{"xdeviceRequest":"wrong","deviceRequest":"right"}"#;
        assert_eq!(find_string_value(json, b"deviceRequest"), Some(&b"right"[..]));
    }

    #[test]
    fn returns_none_when_key_absent() {
        let json = br#"{"foo":"bar"}"#;
        assert!(find_string_value(json, b"deviceRequest").is_none());
    }

    #[test]
    fn requires_protocol_marker_to_match() {
        let s = format!(
            r#"{{"protocol":"openid4vp","data":{{"deviceRequest":"{}"}}}}"#,
            test_support::base64url_no_pad(DOCTYPE.as_bytes()),
        );
        assert!(!request_is_eligible(s.as_bytes()));
    }

    #[test]
    fn matches_on_doctype_in_decoded_device_request() {
        let s = format!(
            r#"{{"requests":[{{"protocol":"org-iso-mdoc","data":{{"deviceRequest":"{}"}}}}]}}"#,
            test_support::base64url_no_pad(DOCTYPE.as_bytes()),
        );
        assert!(request_is_eligible(s.as_bytes()));
    }

    #[test]
    fn matches_escaped_request_json_wrapper() {
        let s = format!(
            "{{\"requestJson\":\"{{\\\"digital\\\":{{\\\"requests\\\":[{{\\\"protocol\\\":\\\"org-iso-mdoc\\\",\\\"data\\\":{{\\\"deviceRequest\\\":\\\"{}\\\"}}}}]}}}}\"}}",
            test_support::base64url_no_pad(DOCTYPE.as_bytes()),
        );
        assert!(request_is_eligible(s.as_bytes()));
    }

    #[test]
    fn rejects_unrelated_doctype() {
        let s = format!(
            r#"{{"requests":[{{"protocol":"org-iso-mdoc","data":{{"deviceRequest":"{}"}}}}]}}"#,
            test_support::base64url_no_pad(b"org.iso.18013.5.1.mDL\xff\x01\x02"),
        );
        assert!(!request_is_eligible(s.as_bytes()));
    }

    #[test]
    fn parses_display_from_blob() {
        let blob = br#"{"credentials":[{"id":"checkin-x","title":"Hello","subtitle":"World"}]}"#;
        let d = parse_display_from_credentials_blob(blob);
        assert_eq!(d.id, "checkin-x");
        assert_eq!(d.title, "Hello");
        assert_eq!(d.subtitle, "World");
    }

    #[test]
    fn entry_icon_is_a_real_png() {
        // PNG signature: 89 50 4E 47 0D 0A 1A 0A.
        assert!(ENTRY_ICON_PNG.starts_with(&[0x89, b'P', b'N', b'G', 0x0d, 0x0a, 0x1a, 0x0a]));
        assert!(ENTRY_ICON_PNG.len() > 1024);
    }
}
